.arch-linux:
  image: library/archlinux:latest
  tags:
    - runner-amd64
  before_script:
    - useradd ci
    - pacman -Syu kde-development-environment-meta sudo base-devel kconfig kcoreaddons gcc-libs glib2 glibc kconfig kcoreaddons kcrash kdbusaddons ki18n kirigami kirigami-addons kwidgetsaddons qt6 --noconfirm

stages:
  - build
  - package
  - deploy

build-arch-package:
  stage: build
  extends:
    - .arch-linux
  script:
    - cmake . -B build
    - cmake --build build
    - cp build/bin/jewels jewels
  artifacts:
    paths:
      - jewels
      - dev.imanuel.jewels.desktop
      - dev.imanuel.jewels.autostart.desktop
      - dev.imanuel.jewels.svg

makepkg-arch:
  stage: package
  extends:
    - .arch-linux
  script:
    - chown -R ci:ci ${CI_PROJECT_DIR}
    - sudo -E -u ci makepkg
  artifacts:
    paths:
      - jewels-${CI_COMMIT_TAG:-1.0.0}-${CI_PIPELINE_IID}-x86_64.pkg.tar.zst

deploy-arch-package:
  stage: deploy
  extends:
    - .arch-linux
  dependencies:
    - makepkg-arch
  script:
    - git clone "https://ci:${CI_GIT_TOKEN}@gitlab.imanuel.dev/packages/arch.git"
    - cp jewels-${CI_COMMIT_TAG}-${CI_PIPELINE_IID}-x86_64.pkg.tar.zst arch/
    - cd arch
    - git switch -c jewels-${CI_COMMIT_TAG}-${CI_PIPELINE_IID}
    - repo-add ulbricht.db.tar.gz jewels-${CI_COMMIT_TAG}-${CI_PIPELINE_IID}-x86_64.pkg.tar.zst
    - git config --global user.email "jewels@ulbricht.cloud"
    - git config --global user.name "Jewly"
    - git commit -am "Added version ${CI_COMMIT_TAG}-${CI_PIPELINE_IID}"
    - git push -o merge_request.create -o merge_request.target=main -o merge_request.merge_when_pipeline_succeeds origin jewels-${CI_COMMIT_TAG}-${CI_PIPELINE_IID}
  rules:
    - if: $CI_COMMIT_TAG
      when: always
    - when: never